import type { Metadata } from "next";
import { Signika_Negative } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";
import Providers from "./lib/redux/provider";
import { PrimeReactProvider } from "primereact/api";

// css
import "./globals.css";
import "primereact/resources/themes/lara-light-blue/theme.css";

const signika_negative = Signika_Negative({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <PrimeReactProvider>
      <html lang="en">
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
              const style = document.createElement('style')
              style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
              style.setAttribute('type', 'text/css')
              document.querySelector('head').prepend(style)
            `,
            }}
          />
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
          />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Signika+Negative:wght@300..700&display=swap"
            rel="stylesheet"
          ></link>
        </head>
        <body className={signika_negative.className}>
          <SessionProvider session={session}>
            <Header></Header>
            <Providers>{children}</Providers>
            <Footer></Footer>
          </SessionProvider>
        </body>
      </html>
    </PrimeReactProvider>
  );
}
